# Generated by Django 4.0.5 on 2022-06-15 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_alter_venda_desconto_alter_venda_impostos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'permissions': (('setar_nfe', 'Usuário pode alterar NFe'), ('dashboard', 'Pode visualizar a dashboard'), ('permissao3', 'Permissão 3'))},
        ),
    ]
