# Generated by Django 4.0.5 on 2022-07-23 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0005_alter_venda_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='valor_custo_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
