# Generated by Django 4.0.5 on 2022-07-25 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_alter_produto_preco_custo'),
        ('vendas', '0006_venda_valor_custo_total'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemdopedido',
            unique_together={('venda', 'produto')},
        ),
    ]
