# Generated by Django 4.0.5 on 2022-07-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0007_alter_itemdopedido_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemdopedido',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('AB', 'Aberta'), ('FC', 'Fechada'), ('PR', 'Processando'), ('DC', 'Desconhecido')], default='DC', max_length=2),
        ),
    ]
