# Generated by Django 4.0.5 on 2022-07-25 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0008_alter_itemdopedido_unique_together_venda_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='status',
        ),
    ]
