# Generated by Django 4.0.5 on 2022-06-15 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_remove_venda_produtos_itensdopedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itensdopedido',
            name='quantidade',
            field=models.FloatField(),
        ),
    ]
