# Generated by Django 4.0.5 on 2022-06-15 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_alter_itensdopedido_quantidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='pessoa',
        ),
        migrations.DeleteModel(
            name='ItensDoPedido',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.DeleteModel(
            name='Venda',
        ),
    ]
